version: "3.8"
services:
  app:
    build: .
    image: integraseller-backend:latest
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_URL=${CLIENT_URL}
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: integraseller
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: